Check if jq is installed

diff --git a/bin/.bin/github b/bin/.bin/github
--- a/bin/.bin/github
+++ b/bin/.bin/github
@@ -4,6 +4,11 @@
 # http://unix.stackexchange.com/questions/63658/redirecting-the-content-of-a-file-to-the-command-echo
 # https://linuxtidbits.wordpress.com/2008/08/11/output-color-on-bash-scripts/
 
+if ! [ -x "$(command -v jq)" ]; then
+  echo 'Error: jq is not installed.' >&2
+  exit 1
+fi
+
 user=$1
 repo=$2
 jq="jq -r"
